# SignalProcessing 도메인 설정

# 기본 훈련 설정
epochs: 200
batch_size: 64
device: 'cuda'

# 데이터 설정
data_path: 'data/signal_dataset'  # 예시 경로
num_workers: 4
sampling_rate: 1000
signal_length: 2048

# 예시 모델 설정 (향후 추가될 모델들을 위한 템플릿)
cnn_eeg:
  num_channels: 64
  num_classes: 4
  kernel_size: 3
  hidden_dim: 128
  dropout: 0.2
  lr: 1e-3
  lr_step: 30
  lr_gamma: 0.5 